# -*- coding: utf-8 -*-
"""COMPS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FO2S874NJxme5tDXyvQd7TR57qOHRq00
"""

from google.colab import drive
drive.mount('/content/gdrive')



import os
os.listdir('/content')

import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np

''' Reading CSV file'''
student_df = pd.read_csv('/content/gdrive/MyDrive/Student Attendance System/student.csv')
# print(student_df.head())

student_df = student_df.fillna(0)
# print(student_df)

student_df['Date'] = pd.to_datetime(student_df['Date'], errors='coerce')
student_df['Week_Number'] = student_df['Date'].dt.weekdays
print(student_df)

