# -*- coding: utf-8 -*-
"""Mech.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11pza-bHE9Ne5T0apgIs4Wf6fJl7afyt2
"""

from google.colab import drive
drive.mount('/content/gdrive')

import os
os.listdir('/content')

import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np

''' Reading CSV file'''
student_df = pd.read_csv('/content/gdrive/MyDrive/Student Attendance System/student.csv')
# print(student_df.head())

''' NaN to Zero '''

student_df = student_df.fillna(0)
# print(student_df)

student_df['Date'] = pd.to_datetime(student_df['Date'], errors='coerce')
student_df['Week_Number'] = student_df['Date'].dt.week
print(student_df)

''' Filtering Data'''

# selecting rows based on condition
week = student_df.loc[(student_df['Week_Number'] == 5) &
			student_df['Branch']]
# print(week)

week = week.loc[:, (week != 0).any(axis=0)]
week = week.loc[(week['Branch'] == 'MECH')]
# print(week)

''' Grouping data on basis of Name ,Month'''

finalweek = week.groupby(['Name','Enrolled_ID']).agg(M1= ('M1','sum'),CP= ('CP','sum'),BEE= ('BEE','sum'),M3= ('M3','sum'),SOM= ('SOM','sum'),THERMO= ('THERMO','sum'),
                                                           HT= ('HT','sum'),DESIGN= ('DESIGN','sum'),MANU= ('MANU','sum'),MD= ('MD','sum'),
                                                           IE= ('IE','sum'),PPE= ('PPE','sum'),Lec_Attended_Percentage= ('Lec_Attended_Percentage','mean'))

print(finalweek)

''' Filtering Data'''

# selecting rows based on condition
week = student_df.loc[(student_df['Week_Number'] == 6) &
			student_df['Branch']]
# print(week)

week = week.loc[:, (week != 0).any(axis=0)]
week = week.loc[(week['Branch'] == 'MECH')]
print(week)

''' Grouping data on basis of Name ,Month'''

finalweek = week.groupby(['Name','Enrolled_ID']).agg(M1= ('M1','sum'),CP= ('CP','sum'),BEE= ('BEE','sum'),M3= ('M3','sum'),SOM= ('SOM','sum'),THERMO= ('THERMO','sum'),
                                                           HT= ('HT','sum'),DESIGN= ('DESIGN','sum'),MANU= ('MANU','sum'),MD= ('MD','sum'),
                                                           IE= ('IE','sum'),PPE= ('PPE','sum'),Lec_Attended_Percentage= ('Lec_Attended_Percentage','mean'))

# print(finalweek)

for i in range(5,7):
  print(f"For week {i}\n")
  # selecting rows based on condition
  week = student_df.loc[(student_df['Week_Number'] == i) &
			student_df['Branch']]
  # print(week)

  week = week.loc[:, (week != 0).any(axis=0)]
  week = week.loc[(week['Branch'] == 'MECH')]
  # print(week)

  ''' Grouping data on basis of Name ,Month'''

  finalweek = week.groupby(['Name','Enrolled_ID']).agg(M1= ('M1','sum'),CP= ('CP','sum'),BEE= ('BEE','sum'),M3= ('M3','sum'),SOM= ('SOM','sum'),THERMO= ('THERMO','sum'),
                                                           HT= ('HT','sum'),DESIGN= ('DESIGN','sum'),MANU= ('MANU','sum'),MD= ('MD','sum'),
                                                           IE= ('IE','sum'),PPE= ('PPE','sum'),Lec_Attended_Percentage= ('Lec_Attended_Percentage','mean'))

  print(finalweek)

